### ISSUE TITLE
fs.Create behaves differently for os filesystem and memory filesystem

### ISSUE THREAD

**Issue by Diaphteiros** [mandelsoft/vfs#4]
Example code:
```golang
package main

import (
	"fmt"
	"github.com/mandelsoft/vfs/pkg/memoryfs"
	"github.com/mandelsoft/vfs/pkg/osfs"
	"github.com/mandelsoft/vfs/pkg/vfs"
)

func main() {
	path := "/tmp/foo/testfile"

	fmt.Println("---osfs---")
	osFs := osfs.New()
	f, err := osFs.Create(path)
	if err == nil {
		f.Close()
	}
	fmt.Println(err)
	f, err = osFs.Create(path)
	if err == nil {
		f.Close()
	}
	fmt.Println(err)

	fmt.Println("---memfs---")
	memFs := memoryfs.New()
	memFs.MkdirAll(vfs.Dir(memFs, path), os.ModeDir|os.ModePerm)
	f, err = memFs.Create(path)
	if err == nil {
		f.Close()
	}
	fmt.Println(err)
	f, err = memFs.Create(path)
	if err == nil {
		f.Close()
	}
	fmt.Println(err)
}
```

Result:
```
---osfs---
<nil>
<nil>
---memfs---
<nil>
file already exists
```

`fs.Create` will never return an `file already exists` error when called on an OS filesystem, because `os.Create` will simply overwrite existing files by definition. The behavior should be identical when called on a memory filesystem, but here an error is returned if the file already exists instead.

**Comment by mandelsoft** [comment]
Fixed,

but the problem still is, what to do with existing non-regular files.
The resulting os error is different for various file types, but those errors do not have an abstraction in Go and are platform dependent.

So I just return ErrExist.
